### ISSUE TITLE
Can't use integer as game_state type

### ISSUE THREAD

**Issue by swerwath** [GamesCrafters/GamesmanMPI#102]
Discovered when attempting to solve `four_to_one.py`. See error below

``` bash
Traceback (most recent call last):
  File "solver_launcher.py", line 96, in <module>
    process.run()
  File "/Users/scott/Desktop/misc/Research/Gamescrafters/GamesmanMPI/src/process.py", line 44, in run
    self.initial_pos.pos in self.resolved
  File "/Users/scott/Desktop/misc/Research/Gamescrafters/GamesmanMPI/src/cache_dict.py", line 79, in __contains__
    return item in self._file_dict
  File "/Users/scott/anaconda3/lib/python3.4/shelve.py", line 102, in __contains__
    return key.encode(self.keyencoding) in self.dict
AttributeError: 'int' object has no attribute 'encode'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58382,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

Appears to be caused by shelve

**Comment by thyrgle** [comment]
Added encode and decode decorators into the utils so a decorator is all that is needed to fix this. Still might not be the best solution...
